### ISSUE TITLE
Reseting scene in Editor recreates armature

### ISSUE THREAD

**Issue by Lcbx** [rokups/rbfx#244] opened 2020-12-06 00:54 UTC
with this scene setup :
![image](https://user-images.githubusercontent.com/10773384/101268506-f06e9100-3763-11eb-839a-7b194cb3f249.png)

when you start the scene then reset it :
![image](https://user-images.githubusercontent.com/10773384/101268535-3b88a400-3764-11eb-974f-6386627d9959.png)

another armature is created :
![image](https://user-images.githubusercontent.com/10773384/101268542-52c79180-3764-11eb-8e24-2b5a881c3f4e.png)

interestingly it is not a clone of the previous armature, so it probably just reloads the .mdl file

**Comment by rokups** [comment] 2020-12-06 11:53
Duplicate of #216. Thanks for reporting though :)

**Closed by rokups** 2020-12-06 11:53 UTC
