### ISSUE TITLE
Editor Crashes In Debug Mode When selecting objects.

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#72] opened 2019-02-16 00:55 UTC
![image](https://user-images.githubusercontent.com/2559371/52891860-f1779e00-314a-11e9-898c-fb4890029883.png)

**Comment by rokups** [comment] 2019-02-16 08:17
I can not reproduce the issue.

**Comment by rokups** [comment] 2019-06-09 08:04
Closing since i could not reproduce it. Reopen with more info if it happens again.

**Closed by rokups** 2019-06-09 08:04 UTC
Labels: area: editor, need more info
