### ISSUE TITLE
Compile error on Visual Studio 2017

### ISSUE THREAD

**Issue by carlcc** [rokups/rbfx#191] opened 2020-02-12 04:58 UTC
Hi, have you tested building on windows? I failed, I cannot build neither building with the cmake generated .sln project nor use visual studio cmake support.

**Comment by eugeneko** [comment] 2020-02-12 07:40
> Hi, have you tested building on windows?

We do have CI for Windows.
https://github.com/rokups/rbfx/runs/437832289

I recommend you to provide more details if you want to get things fixed.

**Comment by bvanevery** [comment] 2020-04-27 19:03
I happened to build on VS 2017 yesterday with no issues.  Default settings only.  Used CMake GUI, did not enter any new information.  Did an out-of-source build.  CMake version 3.17.1.  Windows 10 latest greatest something.

Suggest you close this issue with "cannot reproduce".

**Comment by carlcc** [comment] 2020-04-28 01:59
Sorry to leave this issue for such long time.

My previous visual studio 2017 installed a Chinese language pack, and indeed it failed to compile the source. The error information is also Chinese, so I did not past it here.

I installed vs2019 (and uninstalled 2017) the other day, without Chinese language pack, and I just compiled rbfx successfully.

I suspect the compile error was caused by the language pack?

**Comment by carlcc** [comment] 2020-04-28 02:00
Sorry for close this issue mistakenly.

Uhm... But I think this issue can be closed now. ; -)

**Comment by rokups** [comment] 2020-04-28 06:08
> I suspect the compile error was caused by the language pack?

I can not think of a reason why that would be the case. Anyhow now that issue is solved - closing it. Or you could have left it closed. :confused:

**Closed by rokups** 2020-04-28 06:08 UTC
Labels: bug, low priority, need more info
