### ISSUE TITLE
Context menus appear out of bounds

### ISSUE THREAD

**Issue by eugeneko** [rokups/rbfx#171] opened 2019-12-26 18:50 UTC
![image](https://user-images.githubusercontent.com/8576192/71486923-ae399180-2829-11ea-98cd-eb047ac0087f.png)

And sometimes blurred
![image](https://user-images.githubusercontent.com/8576192/71486916-9eba4880-2829-11ea-9be1-e9cadb604671.png)

Yes, this is the bottom of the screen

**Comment by rokups** [comment] 2019-12-27 09:23
Duplicate of #168.

**Closed by rokups** 2019-12-27 09:23 UTC
Labels: duplicate
