### ISSUE TITLE
Editor: Opening Second Project in Editor Session Does Not Work

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#66] opened 2018-12-20 16:18 UTC
After opening a project in the editor and then subsequently opening another project.  The second project is not loaded and the following message is given:

![image](https://user-images.githubusercontent.com/2559371/50296682-442d2600-0438-11e9-85bf-ff800fde289a.png)

**Comment by rokups** [comment] 2018-12-21 11:47
Please verify with latest master branch. Subprocess workers had quite some work done on them.

**Comment by rokups** [comment] 2019-06-09 08:05
Closing since i could not reproduce it from the start. If it happens again - reopen with more info.

**Closed by rokups** 2019-06-09 08:05 UTC
