### ISSUE TITLE
Visual Studio Configuration Switching

### ISSUE THREAD

**Issue by TrevorCash** [rokups/rbfx#98] opened 2019-06-15 01:31 UTC
I am consistently getting this issue:

1. I make a fresh visual studio solution with cmake (fully fresh build)
2. I do development work in the RelWithDebInfo Configuration
3. I switch to Debug configuration
4. I get these Errors:
![image](https://user-images.githubusercontent.com/2559371/59545386-a55f1f00-8eda-11e9-9710-ac7b7fd77562.png)

Interestingly - If I switch to debug right after making the new solution - things run fine.  
Also I'm not changing any project settings or anything, seems like a visual studio issue but perhaps it could be a cmake issue?

It also will still show the errors when I do a full clean and build from within visual studio.

Thought I would through the issue up here though - its annoying to have to run a full cmake just to switch to Debug configuration.

**Comment by rokups** [comment] 2019-07-13 15:24
There were significant build changes recently. I tested configuration switching today and it seems to be working. Could you please get latest code from master and try again?

**Comment by TrevorCash** [comment] 2019-07-13 19:33
Cool sounds great!  Ill test again.  and If I dont see it I will delete the issue.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by eugeneko** [comment] 2019-07-13 19:42
It seems this is the same issue I've faced today

**Comment by TrevorCash** [comment] 2019-07-14 16:09
The issue seems different now:  I did the following sequence:

1. pulled from master and cleared the build cache
2. built with cmake
3. built project using RelWithDebInfo
4. project compiled and ran successfully.
5. switched to Debug
6. Get the following errors:

![image](https://user-images.githubusercontent.com/2559371/61186154-5adada80-a61f-11e9-94e8-a15389646b62.png)

1>------ Build started: Project: EASTL, Configuration: Debug x64 ------
1>Error: The operation could not be completed. Unspecified error 
2>------ Build started: Project: FreeType, Configuration: Debug x64 ------
2>Error: The operation could not be completed. Unspecified error 
3>------ Build started: Project: STB, Configuration: Debug x64 ------
3>Error: The operation could not be completed. Unspecified error 
4>------ Build started: Project: LZ4, Configuration: Debug x64 ------
4>Error: The operation could not be completed. Unspecified error 
5>------ Build started: Project: PugiXml, Configuration: Debug x64 ------
5>Error: The operation could not be completed. Unspecified error 
========== Build: 0 succeeded, 5 failed, 24 up-to-date, 0 skipped ==========

**Comment by rokups** [comment] 2019-07-14 16:31
> built with cmake


Exactly how, what flags?

**Comment by TrevorCash** [comment] 2019-07-14 16:41
reRunCMake.sh:
```
mkdir build
cd build 
rm -f -r *

cmake .. -G "Visual Studio 15 2017 Win64" \
-DURHO3D_CSHARP=OFF \
-DURHO3D_MONOLITHIC_HEADER=ON \
-DURHO3D_SAMPLES=ON \
-DURHO3D_WIN32_CONSOLE=ON \
-DURHO3D_WEBP=OFF \
-DURHO3D_NAVIGATION=OFF \
-DURHO3D_URHO2D=OFF \
-DURHO3D_NETWORK=OFF \
-DURHO3D_PROFILING=OFF \
-DNEWTON_WITH_AVX2_PLUGIN=ON \
-DNEWTON_DOUBLE_PRECISION=ON

```

The folder structure looks like this:
![image](https://user-images.githubusercontent.com/2559371/61186526-c8890580-a623-11e9-9c6b-7bb942d1c8f6.png)

**Comment by rokups** [comment] 2019-07-14 17:28
I can not reproduce issue as I do not have your project. Can you reproduce 
it with only rbfx or with https://github.com/rokups/rbfx-Sample?

**Comment by TrevorCash** [comment] 2019-07-14 18:07
I'll test with the sample project - Also I went ahead and gave you access to the repo for reference.

**Comment by rokups** [comment] 2019-10-11 07:23
is this still a problem?

**Comment by rokups** [comment] 2021-05-22 10:37
Closing since i can not replicate.

**Closed by rokups** 2021-05-22 10:37 UTC
Labels: area: build system
